version: '3'
services:
  api:
    build: .
    volumes:
      - .:/flask-graphQL-example:cached
    working_dir: "/flask-graphQL-example"
    environment:
      PIPENV_VENV_IN_PROJECT: "1"
      FLASK_APP: "wsgi.py"
      FLASK_DEBUG: "1"
    command: "flask run --host=0.0.0.0"
    links:
      - db
    ports:
      - "5000:5000"
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      MYSQL_DATABASE: "example"
      MYSQL_ROOT_PASSWORD: "root"
    expose:
      - "3306"
    ports:
      - "3306:3306"
